package com.jeiel.test;

public class Data {
	public static String[][] UNDERGRADUATE_DATA=new String[][]{
		{"School of Creative Studies and Media|Chinese and Creative Studies|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T103-Chinese-and-Creative-Studies"},
		{"School of Creative Studies and Media|Creative and Professional Writing|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/W890-Creative-and-Professional-Writing"},
		{"School of Creative Studies and Media|Creative Practice|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/W900-Creative-Practice"},
		{"School of Creative Studies and Media|Creative Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/WPQ0-Creative-Studies"},
		{"School of Creative Studies and Media|Creative Studies and English Language|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/WQ93-Creative-Studies-and-English-Language"},
		{"School of Creative Studies and Media|Creative Studies and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/WR93-Creative-Studies-and-Italian"},
		{"School of Creative Studies and Media|Creative Writing and Media Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/WP83-Creative-Writing-and-Media-Studies"},
		{"School of Creative Studies and Media|English Language with Film Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q3WP-English-Language-with-Film-Studies"},
		{"School of Creative Studies and Media|English Literature with Journalism|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/065C-English-Literature-with-Journalism"},
		{"School of Creative Studies and Media|English Literature with Theatre and Performance|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/32M8-English-Literature-with-Theatre-and-Performance"},
		{"School of Creative Studies and Media|Film Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/W620-Film-Studies"},
		{"School of Creative Studies and Media|Film Studies and Chinese|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T125-Film-Studies-and-Chinese"},
		{"School of Creative Studies and Media|Film Studies with Theatre and Performance|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/P3W5-Film-Studies-with-Theatre-and-Performance"},
		{"School of Creative Studies and Media|Fine Art part-time|BA (Hons)|11750|","http://www.bangor.ac.uk/courses/undergraduate/W103-Fine-Art-part-time"},
		{"School of Creative Studies and Media|French with Journalism|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1P5-French-with-Journalism"},
		{"School of Creative Studies and Media|French with Media Studies|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1P3-French-with-Media-Studies"},
		{"School of Creative Studies and Media|German with Creative Writing|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R2W8-German-with-Creative-Writing"},
		{"School of Creative Studies and Media|History with Film Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/V1W6-History-with-Film-Studies"},
		{"School of Creative Studies and Media|History with Journalism|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/V1P5-History-with-Journalism"},
		{"School of Creative Studies and Media|Journalism and English Language|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/PQ53-Journalism-and-English-Language"},
		{"School of Creative Studies and Media|Journalism and Media Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/PP53-Journalism-and-Media-Studies"},
		{"School of Creative Studies and Media|Media|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/P308-Media"},
		{"School of Creative Studies and Media|Media Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/P306-Media-Studies"},
		{"School of Creative Studies and Media|Media Studies and English|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/PQ3H-Media-Studies-and-English"},
		{"School of Creative Studies and Media|Media Studies with French|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/P3R1-Media-Studies-with-French"},
		{"School of Creative Studies and Media|Media Studies with German|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/P3R2-Media-Studies-with-German"},
		{"School of Creative Studies and Media|Media Studies with Italian|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/P3R3-Media-Studies-with-Italian"},
		{"School of Creative Studies and Media|Media Studies with Spanish|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/P3R4-Media-Studies-with-Spanish"},
		{"School of Creative Studies and Media|Media Studies with Theatre and Performance|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/P3WL-Media-Studies-with-Theatre-and-Performance"},
		{"School of Creative Studies and Media|Music and Creative Writing|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/WW38-Music-and-Creative-Writing"},
		{"School of Creative Studies and Media|Music and Film Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/WW36-Music-and-Film-Studies"},
		{"School of Creative Studies and Media|Professional Writing|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/W891-Professional-Writing"},
		{"School of Creative Studies and Media|Professional Writing and Film|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/W6W8-Professional-Writing-and-Film"},
		{"School of Creative Studies and Media|Professional Writing and Media|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/P3W9-Professional-Writing-and-Media"},
		{"School of English Literature|British and Irish Literatures|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/8H24-British-and-Irish-Literatures"},
		{"School of English Literature|British and Irish Literatures|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/8H27-British-and-Irish-Literatures"},
		{"School of English Literature|Creative and Professional Writing|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/W890-Creative-and-Professional-Writing"},
		{"School of English Literature|English Language and English Literature|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/QQC3-English-Language-and-English-Literature"},
		{"School of English Literature|English Language with Creative Writing|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q3WL-English-Language-with-Creative-Writing"},
		{"School of English Literature|English Language with English Literature|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q3Q2-English-Language-with-English-Literature"},
		{"School of English Literature|English Literature|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/Q320-English-Literature"},
		{"School of English Literature|English Literature|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/8H25-English-Literature"},
		{"School of English Literature|English Literature and Chinese|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T124-English-Literature-and-Chinese"},
		{"School of English Literature|English Literature and Creative Writing|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/2P17-English-Literature-and-Creative-Writing"},
		{"School of English Literature|English Literature and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/09V3-English-Literature-and-Italian"},
		{"School of English Literature|English Literature with Creative Writing|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/2D13-English-Literature-with-Creative-Writing"},
		{"School of English Literature|English Literature with Creative Writing|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/Q2W9-English-Literature-with-Creative-Writing"},
		{"School of English Literature|English Literature with English Language|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q310-English-Literature-with-English-Language"},
		{"School of English Literature|English Literature with Journalism|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/065C-English-Literature-with-Journalism"},
		{"School of English Literature|English Literature with Songwriting|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/3X19-English-Literature-with-Songwriting"},
		{"School of English Literature|English Literature with Theatre and Performance|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/32M8-English-Literature-with-Theatre-and-Performance"},
		{"School of English Literature|Law with English Literature|LLB (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/M1QK-Law-with-English-Literature"},
		{"School of English Literature|Linguistics with English Literature|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q1Q3-Linguistics-with-English-Literature"},
		{"School of English Literature|Media Studies and English|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/PQ3H-Media-Studies-and-English"},
		{"School of History, Welsh History and Archaeology|Archaeology|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/V400-Archaeology"},
		{"School of History, Welsh History and Archaeology|Archaeology|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/V401-Archaeology"},
		{"School of History, Welsh History and Archaeology|Heritage, Archaeology and History|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/VV41-Heritage-Archaeology-and-History"},
		{"School of History, Welsh History and Archaeology|History|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/V100-History"},
		{"School of History, Welsh History and Archaeology|History|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/V101-History"},
		{"School of History, Welsh History and Archaeology|History and Economics|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/LV11-History-and-Economics"},
		{"School of History, Welsh History and Archaeology|History and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RV31-History-and-Italian"},
		{"School of History, Welsh History and Archaeology|History with Archaeology|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/V1V4-History-with-Archaeology"},
		{"School of History, Welsh History and Archaeology|History with Film Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/V1W6-History-with-Film-Studies"},
		{"School of History, Welsh History and Archaeology|History with Journalism|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/V1P5-History-with-Journalism"},
		{"School of History, Welsh History and Archaeology|Medieval and Early Modern History|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/V130-Medieval-and-Early-Modern-History"},
		{"School of History, Welsh History and Archaeology|Modern and Contemporary History|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/V140-Modern-and-Contemporary-History"},
		{"School of History, Welsh History and Archaeology|Philosophy & Religion and History|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/VVV1-Philosophy-Religion-and-History"},
		{"School of History, Welsh History and Archaeology|Philosophy & Religion and Welsh History|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/VVV2-Philosophy-Religion-and-Welsh-History"},
		{"School of History, Welsh History and Archaeology|Social Policy and History|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/LV41-Social-Policy-and-History"},
		{"School of History, Welsh History and Archaeology|Welsh History and History|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/VV12-Welsh-History-and-History"},
		{"School of History, Welsh History and Archaeology|Welsh History with Archaeology|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/V1VK-Welsh-History-with-Archaeology"},
		{"School of Lifelong Learning|Combined Studies part-time|BA (Hons)|11750|","http://www.bangor.ac.uk/courses/undergraduate/Y001-Combined-Studies-part-time"},
		{"School of Lifelong Learning|Fine Art part-time|BA (Hons)|11750|","http://www.bangor.ac.uk/courses/undergraduate/W103-Fine-Art-part-time"},
		{"School of Lifelong Learning|Psychosocial Studies in Substance Use part-time|BA (Hons)|11750|","http://www.bangor.ac.uk/courses/undergraduate/L593-Psychosocial-Studies-in-Substance-Use-part-time"},
		{"School of Linguistics and English Language|Bilingualism|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/Q102-Bilingualism"},
		{"School of Linguistics and English Language|Chinese and Linguistics|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T101-Chinese-and-Linguistics"},
		{"School of Linguistics and English Language|Cognitive Linguistics|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/Q103-Cognitive-Linguistics"},
		{"School of Linguistics and English Language|English Language|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q301-English-Language"},
		{"School of Linguistics and English Language|English Language and Chinese|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T123-English-Language-and-Chinese"},
		{"School of Linguistics and English Language|English Language and English Literature|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/QQC3-English-Language-and-English-Literature"},
		{"School of Linguistics and English Language|English Language and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/QR3H-English-Language-and-Italian"},
		{"School of Linguistics and English Language|English Language for TEFL|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q315-English-Language-for-TEFL"},
		{"School of Linguistics and English Language|English Language for TEFL|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/Q316-English-Language-for-TEFL"},
		{"School of Linguistics and English Language|English Language with Creative Writing|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q3WL-English-Language-with-Creative-Writing"},
		{"School of Linguistics and English Language|English Language with English Literature|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q3Q2-English-Language-with-English-Literature"},
		{"School of Linguistics and English Language|English Language with Film Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q3WP-English-Language-with-Film-Studies"},
		{"School of Linguistics and English Language|English Language with Media Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q3P3-English-Language-with-Media-Studies"},
		{"School of Linguistics and English Language|English Literature with English Language|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q310-English-Literature-with-English-Language"},
		{"School of Linguistics and English Language|International English Language for TEFL|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q314-International-English-Language-for-TEFL"},
		{"School of Linguistics and English Language|Italian and Linguistics|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/QR13-Italian-and-Linguistics"},
		{"School of Linguistics and English Language|Journalism and English Language|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/PQ53-Journalism-and-English-Language"},
		{"School of Linguistics and English Language|Linguistics|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q100-Linguistics"},
		{"School of Linguistics and English Language|Linguistics|MArts|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/Q101-Linguistics"},
		{"School of Linguistics and English Language|Linguistics and the English Language|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q140-Linguistics-and-the-English-Language"},
		{"School of Linguistics and English Language|Linguistics with English Literature|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q1Q3-Linguistics-with-English-Literature"},
		{"School of Linguistics and English Language|Philosophy & Religion and English Literature|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/3VQV-Philosophy-Religion-and-English-Literature"},
		{"School of Modern Languages and Cultures|(European) Law with French|LLB (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/M105--European-Law-with-French"},
		{"School of Modern Languages and Cultures|(European) Law with German|LLB (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/M106--European-Law-with-German"},
		{"School of Modern Languages and Cultures|(European) Law with Italian|LLB (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/M107--European-Law-with-Italian"},
		{"School of Modern Languages and Cultures|(European) Law with Spanish|LLB (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/M109--European-Law-with-Spanish"},
		{"School of Modern Languages and Cultures|Accounting and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/NR43-Accounting-and-Italian"},
		{"School of Modern Languages and Cultures|Banking and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/NR33-Banking-and-Italian"},
		{"School of Modern Languages and Cultures|Business Studies and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/NR1H-Business-Studies-and-Italian"},
		{"School of Modern Languages and Cultures|Business Studies with French|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/N1R1-Business-Studies-with-French"},
		{"School of Modern Languages and Cultures|Business Studies with German|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/N1R2-Business-Studies-with-German"},
		{"School of Modern Languages and Cultures|Business Studies with Italian|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/N1R3-Business-Studies-with-Italian"},
		{"School of Modern Languages and Cultures|Business Studies with Spanish|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/N1R4-Business-Studies-with-Spanish"},
		{"School of Modern Languages and Cultures|Chinese and Creative Studies|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T103-Chinese-and-Creative-Studies"},
		{"School of Modern Languages and Cultures|Chinese and Cymraeg|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T102-Chinese-and-Cymraeg"},
		{"School of Modern Languages and Cultures|Chinese and French|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T104-Chinese-and-French"},
		{"School of Modern Languages and Cultures|Chinese and French with German|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T111-Chinese-and-French-with-German"},
		{"School of Modern Languages and Cultures|Chinese and French with Italian|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T112-Chinese-and-French-with-Italian"},
		{"School of Modern Languages and Cultures|Chinese and French with Spanish|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T113-Chinese-and-French-with-Spanish"},
		{"School of Modern Languages and Cultures|Chinese and German|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T105-Chinese-and-German"},
		{"School of Modern Languages and Cultures|Chinese and German with French|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T114-Chinese-and-German-with-French"},
		{"School of Modern Languages and Cultures|Chinese and German with Italian|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T115-Chinese-and-German-with-Italian"},
		{"School of Modern Languages and Cultures|Chinese and German with Spanish|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T116-Chinese-and-German-with-Spanish"},
		{"School of Modern Languages and Cultures|Chinese and Italian|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T106-Chinese-and-Italian"},
		{"School of Modern Languages and Cultures|Chinese and Italian with French|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T117-Chinese-and-Italian-with-French"},
		{"School of Modern Languages and Cultures|Chinese and Italian with German|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T118-Chinese-and-Italian-with-German"},
		{"School of Modern Languages and Cultures|Chinese and Italian with Spanish|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T119-Chinese-and-Italian-with-Spanish"},
		{"School of Modern Languages and Cultures|Chinese and Linguistics|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T101-Chinese-and-Linguistics"},
		{"School of Modern Languages and Cultures|Chinese and Spanish|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T107-Chinese-and-Spanish"},
		{"School of Modern Languages and Cultures|Chinese and Spanish with French|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T120-Chinese-and-Spanish-with-French"},
		{"School of Modern Languages and Cultures|Chinese and Spanish with German|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T121-Chinese-and-Spanish-with-German"},
		{"School of Modern Languages and Cultures|Chinese and Spanish with Italian|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T122-Chinese-and-Spanish-with-Italian"},
		{"School of Modern Languages and Cultures|Creative Studies and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/WR93-Creative-Studies-and-Italian"},
		{"School of Modern Languages and Cultures|Criminology & Criminal Justice and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/MR93-Criminology-Criminal-Justice-and-Italian"},
		{"School of Modern Languages and Cultures|Economics and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/LR13-Economics-and-Italian"},
		{"School of Modern Languages and Cultures|Economics and Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/LR14-Economics-and-Spanish"},
		{"School of Modern Languages and Cultures|English Language and Chinese|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T123-English-Language-and-Chinese"},
		{"School of Modern Languages and Cultures|English Language and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/QR3H-English-Language-and-Italian"},
		{"School of Modern Languages and Cultures|English Literature and Chinese|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T124-English-Literature-and-Chinese"},
		{"School of Modern Languages and Cultures|English Literature and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/09V3-English-Literature-and-Italian"},
		{"School of Modern Languages and Cultures|Film Studies and Chinese|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T125-Film-Studies-and-Chinese"},
		{"School of Modern Languages and Cultures|French|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R101-French"},
		{"School of Modern Languages and Cultures|French and Economics|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/LR11-French-and-Economics"},
		{"School of Modern Languages and Cultures|French and German|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RR12-French-and-German"},
		{"School of Modern Languages and Cultures|French and German with Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R901-French-and-German-with-Italian"},
		{"School of Modern Languages and Cultures|French and German with Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R913-French-and-German-with-Spanish"},
		{"School of Modern Languages and Cultures|French and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RR13-French-and-Italian"},
		{"School of Modern Languages and Cultures|French and Italian with German|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R918-French-and-Italian-with-German"},
		{"School of Modern Languages and Cultures|French and Italian with Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R919-French-and-Italian-with-Spanish"},
		{"School of Modern Languages and Cultures|French and Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RR14-French-and-Spanish"},
		{"School of Modern Languages and Cultures|French and Spanish with German|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R914-French-and-Spanish-with-German"},
		{"School of Modern Languages and Cultures|French and Spanish with Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R915-French-and-Spanish-with-Italian"},
		{"School of Modern Languages and Cultures|French with Business Studies|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1NC-French-with-Business-Studies"},
		{"School of Modern Languages and Cultures|French with Chinese|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T108-French-with-Chinese"},
		{"School of Modern Languages and Cultures|French with Creative Writing|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1W8-French-with-Creative-Writing"},
		{"School of Modern Languages and Cultures|French with German|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1R2-French-with-German"},
		{"School of Modern Languages and Cultures|French with Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1R3-French-with-Italian"},
		{"School of Modern Languages and Cultures|French with Journalism|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1P5-French-with-Journalism"},
		{"School of Modern Languages and Cultures|French with Marketing|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1N1-French-with-Marketing"},
		{"School of Modern Languages and Cultures|French with Media Studies|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1P3-French-with-Media-Studies"},
		{"School of Modern Languages and Cultures|French with Psychology|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1C8-French-with-Psychology"},
		{"School of Modern Languages and Cultures|French with Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1R4-French-with-Spanish"},
		{"School of Modern Languages and Cultures|French, German and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R916-French-German-and-Italian"},
		{"School of Modern Languages and Cultures|French, German and Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R912-French-German-and-Spanish"},
		{"School of Modern Languages and Cultures|French, Italian and Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R917-French-Italian-and-Spanish"},
		{"School of Modern Languages and Cultures|German|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R200-German"},
		{"School of Modern Languages and Cultures|German and Economics|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/LR12-German-and-Economics"},
		{"School of Modern Languages and Cultures|German and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RR23-German-and-Italian"},
		{"School of Modern Languages and Cultures|German and Italian with French|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R921-German-and-Italian-with-French"},
		{"School of Modern Languages and Cultures|German and Italian with Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R924-German-and-Italian-with-Spanish"},
		{"School of Modern Languages and Cultures|German and Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RR24-German-and-Spanish"},
		{"School of Modern Languages and Cultures|German and Spanish with French|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R922-German-and-Spanish-with-French"},
		{"School of Modern Languages and Cultures|German and Spanish with Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R923-German-and-Spanish-with-Italian"},
		{"School of Modern Languages and Cultures|German with Business Studies|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R2NC-German-with-Business-Studies"},
		{"School of Modern Languages and Cultures|German with Chinese|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T109-German-with-Chinese"},
		{"School of Modern Languages and Cultures|German with Creative Writing|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R2W8-German-with-Creative-Writing"},
		{"School of Modern Languages and Cultures|German with French|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R2R1-German-with-French"},
		{"School of Modern Languages and Cultures|German with Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R2R3-German-with-Italian"},
		{"School of Modern Languages and Cultures|German with Journalism|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R2P5-German-with-Journalism"},
		{"School of Modern Languages and Cultures|German with Marketing|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R2N1-German-with-Marketing"},
		{"School of Modern Languages and Cultures|German with Media Studies|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R2P4-German-with-Media-Studies"},
		{"School of Modern Languages and Cultures|German with Psychology|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R2C8-German-with-Psychology"},
		{"School of Modern Languages and Cultures|German with Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R2R4-German-with-Spanish"},
		{"School of Modern Languages and Cultures|German, Italian and Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R925-German-Italian-and-Spanish"},
		{"School of Modern Languages and Cultures|History and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RV31-History-and-Italian"},
		{"School of Modern Languages and Cultures|Italian and Cymraeg|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/QR53-Italian-and-Cymraeg"},
		{"School of Modern Languages and Cultures|Italian and Linguistics|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/QR13-Italian-and-Linguistics"},
		{"School of Modern Languages and Cultures|Italian and Management|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/NR23-Italian-and-Management"},
		{"School of Modern Languages and Cultures|Italian and Physical Education|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR63-Italian-and-Physical-Education"},
		{"School of Modern Languages and Cultures|Italian and Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RR43-Italian-and-Spanish"},
		{"School of Modern Languages and Cultures|Italian and Spanish with French|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R926-Italian-and-Spanish-with-French"},
		{"School of Modern Languages and Cultures|Italian and Spanish with German|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R927-Italian-and-Spanish-with-German"},
		{"School of Modern Languages and Cultures|Italian and Sport Science|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR6H-Italian-and-Sport-Science"},
		{"School of Modern Languages and Cultures|Marketing and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/NR53-Marketing-and-Italian"},
		{"School of Modern Languages and Cultures|Marketing with French|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/N5R1-Marketing-with-French"},
		{"School of Modern Languages and Cultures|Marketing with German|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/N5R2-Marketing-with-German"},
		{"School of Modern Languages and Cultures|Marketing with Italian|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/N5R3-Marketing-with-Italian"},
		{"School of Modern Languages and Cultures|Marketing with Spanish|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/N5R4-Marketing-with-Spanish"},
		{"School of Modern Languages and Cultures|Media Studies with German|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/P3R2-Media-Studies-with-German"},
		{"School of Modern Languages and Cultures|Media Studies with Italian|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/P3R3-Media-Studies-with-Italian"},
		{"School of Modern Languages and Cultures|Media Studies with Spanish|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/P3R4-Media-Studies-with-Spanish"},
		{"School of Modern Languages and Cultures|Music and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/WR33-Music-and-Italian"},
		{"School of Modern Languages and Cultures|Philosophy & Religion and French|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/VVR1-Philosophy-Religion-and-French"},
		{"School of Modern Languages and Cultures|Philosophy & Religion and German|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/VVR2-Philosophy-Religion-and-German"},
		{"School of Modern Languages and Cultures|Philosophy & Religion and Italian|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/VVR3-Philosophy-Religion-and-Italian"},
		{"School of Modern Languages and Cultures|Philosophy & Religion and Spanish|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/VVR4-Philosophy-Religion-and-Spanish"},
		{"School of Modern Languages and Cultures|Physical Education and French|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC16-Physical-Education-and-French"},
		{"School of Modern Languages and Cultures|Physical Education and French|BSc (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC1P-Physical-Education-and-French"},
		{"School of Modern Languages and Cultures|Physical Education and German|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC26-Physical-Education-and-German"},
		{"School of Modern Languages and Cultures|Physical Education and German|BSc (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC2P-Physical-Education-and-German"},
		{"School of Modern Languages and Cultures|Physical Education and Italian|BSc (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC3P-Physical-Education-and-Italian"},
		{"School of Modern Languages and Cultures|Physical Education and Spanish|BSc (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC4P-Physical-Education-and-Spanish"},
		{"School of Modern Languages and Cultures|Spanish|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R400-Spanish"},
		{"School of Modern Languages and Cultures|Spanish and Physical Education|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR64-Spanish-and-Physical-Education"},
		{"School of Modern Languages and Cultures|Spanish with Business Studies|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R4N1-Spanish-with-Business-Studies"},
		{"School of Modern Languages and Cultures|Spanish with Chinese|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T110-Spanish-with-Chinese"},
		{"School of Modern Languages and Cultures|Spanish with Creative Writing|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R4W8-Spanish-with-Creative-Writing"},
		{"School of Modern Languages and Cultures|Spanish with French|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R4R1-Spanish-with-French"},
		{"School of Modern Languages and Cultures|Spanish with German|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R4R2-Spanish-with-German"},
		{"School of Modern Languages and Cultures|Spanish with Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R4R3-Spanish-with-Italian"},
		{"School of Modern Languages and Cultures|Spanish with Journalism|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R4P5-Spanish-with-Journalism"},
		{"School of Modern Languages and Cultures|Spanish with Marketing|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R4N5-Spanish-with-Marketing"},
		{"School of Modern Languages and Cultures|Spanish with Media Studies|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/R4P3-Spanish-with-Media-Studies"},
		{"School of Modern Languages and Cultures|Sport Science and French|BA (Joint Honours)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR61-Sport-Science-and-French"},
		{"School of Modern Languages and Cultures|Sport Science and French|BSc (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR6C-Sport-Science-and-French"},
		{"School of Modern Languages and Cultures|Sport Science and German|BSc (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR6F-Sport-Science-and-German"},
		{"School of Modern Languages and Cultures|Sport Science and German|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR62-Sport-Science-and-German"},
		{"School of Modern Languages and Cultures|Sport Science and Italian|BSc (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/BC6J-Sport-Science-and-Italian"},
		{"School of Modern Languages and Cultures|Sport Science and Spanish|BSc (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR6L-Sport-Science-and-Spanish"},
		{"School of Modern Languages and Cultures|Sport Science and Spanish|BA (Joint Honours)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR6K-Sport-Science-and-Spanish"},
		{"School of Music|Electronic Engineering and Music|BSc (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/H6W3-Electronic-Engineering-and-Music"},
		{"School of Music|English Literature with Songwriting|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/3X19-English-Literature-with-Songwriting"},
		{"School of Music|Music|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/W300-Music"},
		{"School of Music|Music|BMus (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/W302-Music"},
		{"School of Music|Music and Electronic Engineering|BA (Joint Honours)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/W3H6-Music-and-Electronic-Engineering"},
		{"School of Music|Music and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/WR33-Music-and-Italian"},
		{"School of Music|Philosophy & Religion and Music|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/VVW3-Philosophy-Religion-and-Music"},
		{"School of Philosophy and Religion|Philosophy & Religion and English Literature|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/3VQV-Philosophy-Religion-and-English-Literature"},
		{"School of Philosophy and Religion|Philosophy & Religion and French|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/VVR1-Philosophy-Religion-and-French"},
		{"School of Philosophy and Religion|Philosophy & Religion and German|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/VVR2-Philosophy-Religion-and-German"},
		{"School of Philosophy and Religion|Philosophy & Religion and History|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/VVV1-Philosophy-Religion-and-History"},
		{"School of Philosophy and Religion|Philosophy & Religion and Italian|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/VVR3-Philosophy-Religion-and-Italian"},
		{"School of Philosophy and Religion|Philosophy & Religion and Music|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/VVW3-Philosophy-Religion-and-Music"},
		{"School of Philosophy and Religion|Philosophy & Religion and Spanish|BA (Joint Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/VVR4-Philosophy-Religion-and-Spanish"},
		{"School of Philosophy and Religion|Philosophy & Religion and Welsh|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/VVQ5-Philosophy-Religion-and-Welsh"},
		{"School of Philosophy and Religion|Philosophy & Religion and Welsh History|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/VVV2-Philosophy-Religion-and-Welsh-History"},
		{"School of Philosophy and Religion|Philosophy and Religion|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/VV56-Philosophy-and-Religion"},
		{"School of Welsh|Chinese and Cymraeg|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/T102-Chinese-and-Cymraeg"},
		{"School of Welsh|Cymraeg (Welsh) and Physical Education|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/QC56-Cymraeg-Welsh-and-Physical-Education"},
		{"School of Welsh|Italian and Cymraeg|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/QR53-Italian-and-Cymraeg"},
		{"School of Welsh|Philosophy & Religion and Welsh|BA (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/VVQ5-Philosophy-Religion-and-Welsh"},
		{"School of Welsh|Physical Education and Cymraeg (Welsh)|BSc (Joint Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/XQ3M-Physical-Education-and-Cymraeg-Welsh"},
		{"School of Welsh|Welsh (Cymraeg) (for first- and second-language students)|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/Q562-Welsh-Cymraeg-for-first-and-second-language-students"},
		{"School of Welsh|Welsh for Beginners (Cymraeg i Ddechreuwyr)|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/Q522-Welsh-for-Beginners-Cymraeg-i-Ddechreuwyr"},
		{"School of Welsh|Y Gyfraith Gyda'r Gymraeg (Law with Welsh)|LLB (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/M1Q5-Y-Gyfraith-Gyda-r-Gymraeg-Law-with-Welsh"},
		{"Bangor Business School|Accounting and Banking|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/NN34-Accounting-and-Banking"},
		{"Bangor Business School|Accounting and Banking|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/NN43-Accounting-and-Banking"},
		{"Bangor Business School|Accounting and Economics|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/NL41-Accounting-and-Economics"},
		{"Bangor Business School|Accounting and Finance|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N400-Accounting-and-Finance"},
		{"Bangor Business School|Accounting and Finance|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/NN4H-Accounting-and-Finance"},
		{"Bangor Business School|Accounting and Italian|BA (Hons)|12250|4 years","http://www.bangor.ac.uk/courses/undergraduate/NR43-Accounting-and-Italian"},
		{"Bangor Business School|Banking and Finance|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N322-Banking-and-Finance"},
		{"Bangor Business School|Banking and Finance|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N391-Banking-and-Finance"},
		{"Bangor Business School|Banking and Italian|BA (Hons)|12250|4 years","http://www.bangor.ac.uk/courses/undergraduate/NR33-Banking-and-Italian"},
		{"Bangor Business School|Business and Computer Information Systems|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/NG10-Business-and-Computer-Information-Systems"},
		{"Bangor Business School|Business and Law|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/NM11-Business-and-Law"},
		{"Bangor Business School|Business Economics|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/L190-Business-Economics"},
		{"Bangor Business School|Business Studies|HND|12250|2 years","http://www.bangor.ac.uk/courses/undergraduate/022N-Business-Studies"},
		{"Bangor Business School|Business Studies|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N100-Business-Studies"},
		{"Bangor Business School|Business Studies|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N101-Business-Studies"},
		{"Bangor Business School|Business Studies and Finance|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/NN13-Business-Studies-and-Finance"},
		{"Bangor Business School|Business Studies and Finance|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/NN1H-Business-Studies-and-Finance"},
		{"Bangor Business School|Business Studies and Italian|BA (Hons)|12250|4 years","http://www.bangor.ac.uk/courses/undergraduate/NR1H-Business-Studies-and-Italian"},
		{"Bangor Business School|Business Studies and Marketing|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/NN15-Business-Studies-and-Marketing"},
		{"Bangor Business School|Business Studies and Marketing|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/NN1M-Business-Studies-and-Marketing"},
		{"Bangor Business School|Business Studies with French|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N1R1-Business-Studies-with-French"},
		{"Bangor Business School|Business Studies with German|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N1R2-Business-Studies-with-German"},
		{"Bangor Business School|Business Studies with Italian|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N1R3-Business-Studies-with-Italian"},
		{"Bangor Business School|Business Studies with Spanish|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N1R4-Business-Studies-with-Spanish"},
		{"Bangor Business School|Economics and Italian|BA (Hons)|12250|4 years","http://www.bangor.ac.uk/courses/undergraduate/LR13-Economics-and-Italian"},
		{"Bangor Business School|Economics and Spanish|BA (Hons)|12250|4 years","http://www.bangor.ac.uk/courses/undergraduate/LR14-Economics-and-Spanish"},
		{"Bangor Business School|Financial Economics|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/L111-Financial-Economics"},
		{"Bangor Business School|French and Economics|BA (Hons)|12250|4 years","http://www.bangor.ac.uk/courses/undergraduate/LR11-French-and-Economics"},
		{"Bangor Business School|French with Marketing|BA (Hons)|12250|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1N1-French-with-Marketing"},
		{"Bangor Business School|German and Economics|BA (Hons)|12250|4 years","http://www.bangor.ac.uk/courses/undergraduate/LR12-German-and-Economics"},
		{"Bangor Business School|History and Economics|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/LV11-History-and-Economics"},
		{"Bangor Business School|Italian and Management|BA (Hons)|12250|4 years","http://www.bangor.ac.uk/courses/undergraduate/NR23-Italian-and-Management"},
		{"Bangor Business School|Management with Accounting|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N2N4-Management-with-Accounting"},
		{"Bangor Business School|Management with Accounting|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N2NK-Management-with-Accounting"},
		{"Bangor Business School|Marketing|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N500-Marketing"},
		{"Bangor Business School|Marketing|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N501-Marketing"},
		{"Bangor Business School|Marketing and Italian|BA (Hons)|12250|4 years","http://www.bangor.ac.uk/courses/undergraduate/NR53-Marketing-and-Italian"},
		{"Bangor Business School|Marketing with French|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N5R1-Marketing-with-French"},
		{"Bangor Business School|Marketing with German|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N5R2-Marketing-with-German"},
		{"Bangor Business School|Marketing with Italian|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N5R3-Marketing-with-Italian"},
		{"Bangor Business School|Marketing with Spanish|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/N5R4-Marketing-with-Spanish"},
		{"Bangor Business School|Psychology with Business|BSc (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/2R87-Psychology-with-Business"},
		{"Bangor Business School|Social Policy and Economics|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/LL14-Social-Policy-and-Economics"},
		{"Bangor Business School|Sociology and Economics|BA (Hons)|12250|3 years","http://www.bangor.ac.uk/courses/undergraduate/LL13-Sociology-and-Economics"},
		{"School of Education|Childhood Studies|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/X306-Childhood-Studies"},
		{"School of Education|Design and Technology Secondary Education|BSc (Hons) with QTS|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/X1WF-Design-and-Technology-Secondary-Education"},
		{"School of Education|Early Childhood and Learning Support Studies|FdA|11750|","http://www.bangor.ac.uk/courses/undergraduate/X312-Early-Childhood-and-Learning-Support-Studies"},
		{"School of Education|Primary Education|BA (Hons) with QTS|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/X120-Primary-Education"},
		{"School of Education|Product Design|BSc (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/W240-Product-Design"},
		{"School of Law|(European) Law with French|LLB (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/M105--European-Law-with-French"},
		{"School of Law|(European) Law with German|LLB (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/M106--European-Law-with-German"},
		{"School of Law|(European) Law with Italian|LLB (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/M107--European-Law-with-Italian"},
		{"School of Law|(European) Law with Spanish|LLB (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/M109--European-Law-with-Spanish"},
		{"School of Law|Business and Law|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/NM11-Business-and-Law"},
		{"School of Law|English Law and French Law|LLB|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/M1M0-English-Law-and-French-Law"},
		{"School of Law|Law|LLB (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/M100-Law"},
		{"School of Law|Law (2-Year Degree Scheme)|LLB (Hons)|11750|2 years","http://www.bangor.ac.uk/courses/undergraduate/M101-Law-2-Year-Degree-Scheme"},
		{"School of Law|Law with Accounting and Finance|LLB (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/M1N4-Law-with-Accounting-and-Finance"},
		{"School of Law|Law with Business Studies|LLB (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/M1N1-Law-with-Business-Studies"},
		{"School of Law|Law with Contemporary Chinese Studies|LLB (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/MT10-Law-with-Contemporary-Chinese-Studies"},
		{"School of Law|Law with Criminology|LLB (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/M1M9-Law-with-Criminology"},
		{"School of Law|Law with English Literature|LLB (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/M1QK-Law-with-English-Literature"},
		{"School of Law|Law with Professional English (for International Students)|LLB (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/M1QH-Law-with-Professional-English-for-International-Students"},
		{"School of Law|Law with Social Policy|LLB (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/M1L4-Law-with-Social-Policy"},
		{"School of Law|Y Gyfraith Gyda'r Gymraeg (Law with Welsh)|LLB (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/M1Q5-Y-Gyfraith-Gyda-r-Gymraeg-Law-with-Welsh"},
		{"School of Social Sciences|Childhood Studies and Social Policy|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/LXL3-Childhood-Studies-and-Social-Policy"},
		{"School of Social Sciences|Criminology & Criminal Justice and Italian|BA (Hons)|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/MR93-Criminology-Criminal-Justice-and-Italian"},
		{"School of Social Sciences|Criminology and Criminal Justice|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/M930-Criminology-and-Criminal-Justice"},
		{"School of Social Sciences|Criminology and Criminal Justice|MSocSci|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/M932-Criminology-and-Criminal-Justice"},
		{"School of Social Sciences|Cymdeithaseg gyda Pholisi Cymdeithasol (Sociology with Social Policy)|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/L3LK-Cymdeithaseg-gyda-Pholisi-Cymdeithasol-Sociology-with-Social-Policy"},
		{"School of Social Sciences|Cymdeithaseg gyda Pholisi Cymdeithasol (Sociology with Social Policy)|MSocSci|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/L3L5-Cymdeithaseg-gyda-Pholisi-Cymdeithasol-Sociology-with-Social-Policy"},
		{"School of Social Sciences|Health & Social Care and Social Policy|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/LL54-Health-Social-Care-and-Social-Policy"},
		{"School of Social Sciences|Health and Social Care|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/L510-Health-and-Social-Care"},
		{"School of Social Sciences|Health and Social Care|MSocSci|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/L514-Health-and-Social-Care"},
		{"School of Social Sciences|Social Policy|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/L402-Social-Policy"},
		{"School of Social Sciences|Social Policy|MSocSci|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/L403-Social-Policy"},
		{"School of Social Sciences|Social Policy and Criminology & Criminal Justice|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/LM49-Social-Policy-and-Criminology-Criminal-Justice"},
		{"School of Social Sciences|Social Policy and Economics|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/LL14-Social-Policy-and-Economics"},
		{"School of Social Sciences|Social Policy and History|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/LV41-Social-Policy-and-History"},
		{"School of Social Sciences|Social Policy and Psychology|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/CL84-Social-Policy-and-Psychology"},
		{"School of Social Sciences|Societal Health|BSc (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/L431-Societal-Health"},
		{"School of Social Sciences|Societal Health|MSocSci|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/L433-Societal-Health"},
		{"School of Social Sciences|Sociology|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/L300-Sociology"},
		{"School of Social Sciences|Sociology|MSocSci|11750|4 years","http://www.bangor.ac.uk/courses/undergraduate/L302-Sociology"},
		{"School of Social Sciences|Sociology and Economics|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/LL13-Sociology-and-Economics"},
		{"School of Social Sciences|Sociology and Social Policy|BA (Hons)|11750|3 years","http://www.bangor.ac.uk/courses/undergraduate/LL34-Sociology-and-Social-Policy"},
		{"School of Healthcare Sciences|Adult Nursing|BN (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B740-Adult-Nursing"},
		{"School of Healthcare Sciences|Children's Nursing|BN (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B731-Children-s-Nursing"},
		{"School of Healthcare Sciences|Critical Care (Coronary Care)|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B771-Critical-Care-Coronary-Care"},
		{"School of Healthcare Sciences|Critical Care (High Dependency)|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B772-Critical-Care-High-Dependency"},
		{"School of Healthcare Sciences|Critical Care (Intensive Care)|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B773-Critical-Care-Intensive-Care"},
		{"School of Healthcare Sciences|Critical Care (Renal)|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B774-Critical-Care-Renal"},
		{"School of Healthcare Sciences|Diagnostic Radiography|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B821-Diagnostic-Radiography"},
		{"School of Healthcare Sciences|Health Studies (Nursing)|BSc (Hons)|13300|2 years","http://www.bangor.ac.uk/courses/undergraduate/B701-Health-Studies-Nursing"},
		{"School of Healthcare Sciences|Learning Disability Nursing|BN (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B761-Learning-Disability-Nursing"},
		{"School of Healthcare Sciences|Mental Health Nursing|BN (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B760-Mental-Health-Nursing"},
		{"School of Healthcare Sciences|Midwifery|BM (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B720-Midwifery"},
		{"School of Medical Sciences|Biomedical Science|BSc (Hons)|13300|","http://www.bangor.ac.uk/courses/undergraduate/B102-Biomedical-Science"},
		{"School of Medical Sciences|Medical Biology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B103-Medical-Biology"},
		{"School of Medical Sciences|Medical Biology|MBiol|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/B104-Medical-Biology"},
		{"School of Medical Sciences|Medical Sciences|BMedSci (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/B100-Medical-Sciences"},
		{"School of Psychology|French with Psychology|BA (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/R1C8-French-with-Psychology"},
		{"School of Psychology|German with Psychology|BA (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/R2C8-German-with-Psychology"},
		{"School of Psychology|Neuropsychology|BSc (Intercalated)|13300|1 years","http://www.bangor.ac.uk/courses/undergraduate/6S26-Neuropsychology"},
		{"School of Psychology|Psychology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C800-Psychology"},
		{"School of Psychology|Psychology|MSci|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C807-Psychology"},
		{"School of Psychology|Psychology with Business|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/2R87-Psychology-with-Business"},
		{"School of Psychology|Psychology with Clinical and Health Psychology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C880-Psychology-with-Clinical-and-Health-Psychology"},
		{"School of Psychology|Psychology with Clinical and Health Psychology|MSci|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C808-Psychology-with-Clinical-and-Health-Psychology"},
		{"School of Psychology|Psychology with Neuropsychology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C801-Psychology-with-Neuropsychology"},
		{"School of Psychology|Social Policy and Psychology|BA (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/CL84-Social-Policy-and-Psychology"},
		{"School of Sport, Health and Exercise Sciences|Cymraeg (Welsh) and Physical Education|BA (Joint Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/QC56-Cymraeg-Welsh-and-Physical-Education"},
		{"School of Sport, Health and Exercise Sciences|Exercise Physiology|BSc (Intercalated)|13300|1 years","http://www.bangor.ac.uk/courses/undergraduate/B120-Exercise-Physiology"},
		{"School of Sport, Health and Exercise Sciences|Exercise, Behaviour Change and Disease Prevention|BSc (Intercalated)|13300|1 years","http://www.bangor.ac.uk/courses/undergraduate/C882-Exercise-Behaviour-Change-and-Disease-Prevention"},
		{"School of Sport, Health and Exercise Sciences|Italian and Physical Education|BA (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR63-Italian-and-Physical-Education"},
		{"School of Sport, Health and Exercise Sciences|Italian and Sport Science|BA (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR6H-Italian-and-Sport-Science"},
		{"School of Sport, Health and Exercise Sciences|Physical Education and Cymraeg (Welsh)|BSc (Joint Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/XQ3M-Physical-Education-and-Cymraeg-Welsh"},
		{"School of Sport, Health and Exercise Sciences|Physical Education and French|BA (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC16-Physical-Education-and-French"},
		{"School of Sport, Health and Exercise Sciences|Physical Education and French|BSc (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC1P-Physical-Education-and-French"},
		{"School of Sport, Health and Exercise Sciences|Physical Education and German|BA (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC26-Physical-Education-and-German"},
		{"School of Sport, Health and Exercise Sciences|Physical Education and German|BSc (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC2P-Physical-Education-and-German"},
		{"School of Sport, Health and Exercise Sciences|Physical Education and Italian|BSc (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC3P-Physical-Education-and-Italian"},
		{"School of Sport, Health and Exercise Sciences|Physical Education and Spanish|BSc (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/RC4P-Physical-Education-and-Spanish"},
		{"School of Sport, Health and Exercise Sciences|Spanish and Physical Education|BA (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR64-Spanish-and-Physical-Education"},
		{"School of Sport, Health and Exercise Sciences|Sport and Exercise Psychology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C680-Sport-and-Exercise-Psychology"},
		{"School of Sport, Health and Exercise Sciences|Sport Science|BSc (Intercalated)|13300|1 years","http://www.bangor.ac.uk/courses/undergraduate/C603-Sport-Science"},
		{"School of Sport, Health and Exercise Sciences|Sport Science|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C600-Sport-Science"},
		{"School of Sport, Health and Exercise Sciences|Sport Science|MSci|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C607-Sport-Science"},
		{"School of Sport, Health and Exercise Sciences|Sport Science (Outdoor Activities)|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C602-Sport-Science-Outdoor-Activities"},
		{"School of Sport, Health and Exercise Sciences|Sport Science (Outdoor Activities)|MSci|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C609-Sport-Science-Outdoor-Activities"},
		{"School of Sport, Health and Exercise Sciences|Sport Science (Outdoor Recreation)|BSc Top-up Degree|13300|1 years","http://www.bangor.ac.uk/courses/undergraduate/C615-Sport-Science-Outdoor-Recreation"},
		{"School of Sport, Health and Exercise Sciences|Sport Science (Outdoor Recreation)|Foundation Degree|13300|2 years","http://www.bangor.ac.uk/courses/undergraduate/C606-Sport-Science-Outdoor-Recreation"},
		{"School of Sport, Health and Exercise Sciences|Sport Science and French|BA (Joint Honours)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR61-Sport-Science-and-French"},
		{"School of Sport, Health and Exercise Sciences|Sport Science and French|BSc (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR6C-Sport-Science-and-French"},
		{"School of Sport, Health and Exercise Sciences|Sport Science and German|BSc (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR6F-Sport-Science-and-German"},
		{"School of Sport, Health and Exercise Sciences|Sport Science and German|BA (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR62-Sport-Science-and-German"},
		{"School of Sport, Health and Exercise Sciences|Sport Science and Italian|BSc (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/BC6J-Sport-Science-and-Italian"},
		{"School of Sport, Health and Exercise Sciences|Sport Science and Spanish|BSc (Joint Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR6L-Sport-Science-and-Spanish"},
		{"School of Sport, Health and Exercise Sciences|Sport Science and Spanish|BA (Joint Honours)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/CR6K-Sport-Science-and-Spanish"},
		{"School of Sport, Health and Exercise Sciences|Sport, Health and Exercise Science|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/CB69-Sport-Health-and-Exercise-Science"},
		{"School of Sport, Health and Exercise Sciences|Sport, Health and Exercise Science|MSci|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C608-Sport-Health-and-Exercise-Science"},
		{"School of Sport, Health and Exercise Sciences|Sport, Health and Physical Education|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C651-Sport-Health-and-Physical-Education"},
		{"School of Environment, Natural Resources and Geography|Applied Terrestrial and Marine Ecology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C180-Applied-Terrestrial-and-Marine-Ecology"},
		{"School of Environment, Natural Resources and Geography|Applied Terrestrial and Marine Ecology (with placement year)|BSc (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C183-Applied-Terrestrial-and-Marine-Ecology-with-placement-year"},
		{"School of Environment, Natural Resources and Geography|Conservation with Forestry|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/5DKD-Conservation-with-Forestry"},
		{"School of Environment, Natural Resources and Geography|Conservation with Forestry (with placement year)|BSc (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/5DLD-Conservation-with-Forestry-with-placement-year"},
		{"School of Environment, Natural Resources and Geography|Environmental Conservation|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/D447-Environmental-Conservation"},
		{"School of Environment, Natural Resources and Geography|Environmental Conservation (with placement year)|BSc (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/D448-Environmental-Conservation-with-placement-year"},
		{"School of Environment, Natural Resources and Geography|Environmental Management|MEnvSci|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/D450-Environmental-Management"},
		{"School of Environment, Natural Resources and Geography|Environmental Management|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/F854-Environmental-Management"},
		{"School of Environment, Natural Resources and Geography|Environmental Science|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/F900-Environmental-Science"},
		{"School of Environment, Natural Resources and Geography|Environmental Science|MEnvSci|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/F850-Environmental-Science"},
		{"School of Environment, Natural Resources and Geography|Forestry|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/D500-Forestry"},
		{"School of Environment, Natural Resources and Geography|Forestry|MFor|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/D512-Forestry"},
		{"School of Environment, Natural Resources and Geography|Forestry (with placement year)|BSc (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/D501-Forestry-with-placement-year"},
		{"School of Environment, Natural Resources and Geography|Geography|BA (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/L700-Geography"},
		{"School of Environment, Natural Resources and Geography|Geography|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/F800-Geography"},
		{"School of Environment, Natural Resources and Geography|Geography|MGeog|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/F801-Geography"},
		{"School of Biological Sciences|Biology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C100-Biology"},
		{"School of Biological Sciences|Biology|MBiol|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C101-Biology"},
		{"School of Biological Sciences|Biology with Biotechnology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C511-Biology-with-Biotechnology"},
		{"School of Biological Sciences|Biology with Biotechnology|MBiol|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C510-Biology-with-Biotechnology"},
		{"School of Biological Sciences|Marine Biology and Zoology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/CC13-Marine-Biology-and-Zoology"},
		{"School of Biological Sciences|Zoology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C300-Zoology"},
		{"School of Biological Sciences|Zoology|MZool|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C301-Zoology"},
		{"School of Biological Sciences|Zoology with Animal Behaviour|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C3D3-Zoology-with-Animal-Behaviour"},
		{"School of Biological Sciences|Zoology with Animal Behaviour|MZool (Animal Behaviour)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C302-Zoology-with-Animal-Behaviour"},
		{"School of Biological Sciences|Zoology with Climate Change Studies|MZool (Climate Change)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C321-Zoology-with-Climate-Change-Studies"},
		{"School of Biological Sciences|Zoology with Climate Change Studies|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C319-Zoology-with-Climate-Change-Studies"},
		{"School of Biological Sciences|Zoology with Conservation|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C3L2-Zoology-with-Conservation"},
		{"School of Biological Sciences|Zoology with Conservation|MZool (Conservation)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/CD34-Zoology-with-Conservation"},
		{"School of Biological Sciences|Zoology with Evolution|MZool (Evolution)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C322-Zoology-with-Evolution"},
		{"School of Biological Sciences|Zoology with Evolution|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C323-Zoology-with-Evolution"},
		{"School of Biological Sciences|Zoology with Herpetology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C304-Zoology-with-Herpetology"},
		{"School of Biological Sciences|Zoology with Herpetology|MZool (Herpetology)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C303-Zoology-with-Herpetology"},
		{"School of Biological Sciences|Zoology with Marine Zoology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C350-Zoology-with-Marine-Zoology"},
		{"School of Biological Sciences|Zoology with Marine Zoology|MZool (Marine Zoology)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C352-Zoology-with-Marine-Zoology"},
		{"School of Ocean Sciences|Applied Marine Biology|BSc (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C163-Applied-Marine-Biology"},
		{"School of Ocean Sciences|Coastal Geography|BSc (Hons)|13300|","http://www.bangor.ac.uk/courses/undergraduate/F841-Coastal-Geography"},
		{"School of Ocean Sciences|Computing and Oceanography|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/GF07-Computing-and-Oceanography"},
		{"School of Ocean Sciences|Geological Oceanography|MOcean|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/F651-Geological-Oceanography"},
		{"School of Ocean Sciences|Geological Oceanography|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/F650-Geological-Oceanography"},
		{"School of Ocean Sciences|Marine Biology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C160-Marine-Biology"},
		{"School of Ocean Sciences|Marine Biology and Oceanography|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/CF17-Marine-Biology-and-Oceanography"},
		{"School of Ocean Sciences|Marine Biology and Zoology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/CC13-Marine-Biology-and-Zoology"},
		{"School of Ocean Sciences|Marine Environmental Studies|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/F710-Marine-Environmental-Studies"},
		{"School of Ocean Sciences|Marine Geography|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/F842-Marine-Geography"},
		{"School of Ocean Sciences|Marine Vertebrate Zoology|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/C351-Marine-Vertebrate-Zoology"},
		{"School of Ocean Sciences|Master of Marine Biology|MMBiol|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/C161-Master-of-Marine-Biology"},
		{"School of Ocean Sciences|Master of Marine Science|MMSci|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/F711-Master-of-Marine-Science"},
		{"School of Ocean Sciences|Ocean and Geophysics|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/F7F6-Ocean-and-Geophysics"},
		{"School of Ocean Sciences|Ocean Science|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/F700-Ocean-Science"},
		{"School of Ocean Sciences|Oceanography and Computing|MOcean|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/F7G1-Oceanography-and-Computing"},
		{"School of Ocean Sciences|Physical Oceanography|MOcean|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/F732-Physical-Oceanography"},
		{"School of Chemistry|Chemistry|MChem|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/F104-Chemistry"},
		{"School of Chemistry|Chemistry|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/F100-Chemistry"},
		{"School of Chemistry|Chemistry with European Experience|BSc (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/F102-Chemistry-with-European-Experience"},
		{"School of Chemistry|Chemistry with Industrial Experience|MChem|13300|5 years","http://www.bangor.ac.uk/courses/undergraduate/F101-Chemistry-with-Industrial-Experience"},
		{"School of Chemistry|Chemistry with Industrial Experience|BSc (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/F103-Chemistry-with-Industrial-Experience"},
		{"School of Computer Science|Computer Information Systems|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/I110-Computer-Information-Systems"},
		{"School of Computer Science|Computer Information Systems for Business|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/IN00-Computer-Information-Systems-for-Business"},
		{"School of Computer Science|Computer Science|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/G400-Computer-Science"},
		{"School of Computer Science|Computer Science for Business|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/GN41-Computer-Science-for-Business"},
		{"School of Computer Science|Computing and Oceanography|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/GF07-Computing-and-Oceanography"},
		{"School of Computer Science|Creative Technologies|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/GW49-Creative-Technologies"},
		{"School of Computer Science|Oceanography and Computing|MOcean|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/F7G1-Oceanography-and-Computing"},
		{"School of Electronic Engineering|Computer Systems Engineering|BEng (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/H612-Computer-Systems-Engineering"},
		{"School of Electronic Engineering|Computer Systems Engineering|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/H603-Computer-Systems-Engineering"},
		{"School of Electronic Engineering|Computer Systems Engineering|MEng|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/H617-Computer-Systems-Engineering"},
		{"School of Electronic Engineering|Control and Instrumentation Engineering|MEng|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/H661-Control-and-Instrumentation-Engineering"},
		{"School of Electronic Engineering|Critical Safety Engineering|MEng (Hons)|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/H660-Critical-Safety-Engineering"},
		{"School of Electronic Engineering|Electronic Engineering|BSc (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/H611-Electronic-Engineering"},
		{"School of Electronic Engineering|Electronic Engineering|BEng (Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/H610-Electronic-Engineering"},
		{"School of Electronic Engineering|Electronic Engineering|MEng|13300|4 years","http://www.bangor.ac.uk/courses/undergraduate/H601-Electronic-Engineering"},
		{"School of Electronic Engineering|Electronic Engineering and Music|BSc (Joint Hons)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/H6W3-Electronic-Engineering-and-Music"},
		{"School of Electronic Engineering|Music and Electronic Engineering|BA (Joint Honours)|13300|3 years","http://www.bangor.ac.uk/courses/undergraduate/W3H6-Music-and-Electronic-Engineering"},
	};

}
